### ISSUE TITLE
Capy64 fails to resize on windows

### ISSUE THREAD

**Issue by bananasov** [Capy64/Capy64#9]
**Side**
- [ ] Lua side
- [x] C# side
- [ ] Other
- [ ] I don't know

**Describe the bug**
Capy64 crashes on commit `444652da127f49d277c5f6853289ac277b0c2b6d` saying that it can not load `libSDL2-2.0.so.0`.

This might be because of [these](https://github.com/Ale32bit/Capy64/blob/444652da127f49d277c5f6853289ac277b0c2b6d/Capy64/Extensions/Bindings/SDL2.cs#L23-L31) lines as the binaries are built on Linux and not Windows.

**To Reproduce**
1. Open Capy64
2. Resize window
3. See error

**Expected behavior**
Properly resize the window

**Screenshots**
![image](https://user-images.githubusercontent.com/56086819/220853467-47e3e121-2fa9-47c5-8aea-8e848debc6a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox 109.0.1
 - Version: Windows 10 Pro 10.0.19045 Build 19045

**Additional context**
Full error message:
```
crit: Microsoft.Extensions.Hosting.Internal.ApplicationLifetime[6]
      An error occurred starting the application
      System.AggregateException: One or more errors occurred. (Unable to load DLL 'libSDL2-2.0.so.0' or one of its dependencies: The specified module could not be found. (0x8007007E))
       ---> System.DllNotFoundException: Unable to load DLL 'libSDL2-2.0.so.0' or one of its dependencies: The specified module could not be found. (0x8007007E)
         at Capy64.Extensions.Bindings.SDL2.SDL_GetWindowFlags(IntPtr window)
         at Capy64.Extensions.GameWindowExtensions.IsMaximized(GameWindow window) in /home/runner/work/Capy64/Capy64/Capy64/Extensions/GameWindowExtensions.cs:line 70
         at Capy64.Capy64.OnWindowSizeChange(Object sender, EventArgs e) in /home/runner/work/Capy64/Capy64/Capy64/Capy64.cs:line 122
         at Microsoft.Xna.Framework.SdlGameWindow.ClientResize(Int32 width, Int32 height)
         at Microsoft.Xna.Framework.SdlGamePlatform.SdlRunLoop()
         at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
         at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         --- End of inner exception stack trace ---
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
```

**Comment by Ale32bit** [comment]
Fixed in 240efdc493b5f927d0e87b267474a615f1163146
